##############################################################
#####################  RESET DATABASE  #######################
##############################################################
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS ChiNhanh;
DROP TABLE IF EXISTS ChiNhanh_ID;
DROP TABLE IF EXISTS HinhAnhChiNhanh;
DROP TABLE IF EXISTS VatTu;
DROP TABLE IF EXISTS PhongThue;
DROP TABLE IF EXISTS Phong;
DROP TABLE IF EXISTS Khu;
DROP TABLE IF EXISTS ChiNhanh_LoaiPhong;
DROP TABLE IF EXISTS CungCapVatTu;
DROP TABLE IF EXISTS HinhAnhCuaHang;
DROP TABLE IF EXISTS KhungGioHoatDong;
DROP TABLE IF EXISTS MatBang;
DROP TABLE IF EXISTS DichVu;
DROP TABLE IF EXISTS DichVu_ID;
DROP TABLE IF EXISTS DichVuNhaHang;
DROP TABLE IF EXISTS DichVuSpa;
DROP TABLE IF EXISTS DoanhNghiep;
DROP TABLE IF EXISTS DoanhNghiep_ID;
DROP TABLE IF EXISTS HoaDonGoiDichVu;
DROP TABLE IF EXISTS HoaDon;
DROP TABLE IF EXISTS HoaDon_ID;
DROP TABLE IF EXISTS DonDatPhong;
DROP TABLE IF EXISTS DonDatPhong_ID;
DROP TABLE IF EXISTS GoiDichVu;
DROP TABLE IF EXISTS ThongTinGiuong;
DROP TABLE IF EXISTS LoaiVatTu_LoaiPhong;
DROP TABLE IF EXISTS LoaiHangDoLuuNiem;
DROP TABLE IF EXISTS ThuongHieuDoLuuNiem;
DROP TABLE IF EXISTS LoaiPhong;
DROP TABLE IF EXISTS LoaiVatTu;
DROP TABLE IF EXISTS LoaiVatTu_ID;
DROP TABLE IF EXISTS KhachHang;
DROP TABLE IF EXISTS KhachHang_ID;
DROP TABLE IF EXISTS NhaCungCap;
DROP TABLE IF EXISTS NhaCungCap_ID;
